"""empty message

Revision ID: 4296487095bc
Revises: d5f39390c8db
Create Date: 2024-05-30 16:26:53.151231

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4296487095bc"
down_revision = "d5f39390c8db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_teams")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_column("Rank")
        batch_op.drop_column("logo")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("logo", sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column("Rank", sa.INTEGER(), nullable=True))

    op.create_table(
        "_alembic_tmp_teams",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("city", sa.VARCHAR(), nullable=False),
        sa.Column("logo", sa.VARCHAR(), nullable=True),
        sa.Column("rank", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
