"""empty message

Revision ID: 69ec92ba7b39
Revises: faffb8d64471
Create Date: 2024-05-30 23:13:32.591731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ec92ba7b39'
down_revision = 'faffb8d64471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('home_team', sa.VARCHAR(length=100), nullable=False),
    sa.Column('away_team', sa.VARCHAR(length=100), nullable=False),
    sa.Column('home_team_score', sa.INTEGER(), nullable=False),
    sa.Column('away_team_score', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
