"""add rank and logo to teams

Revision ID: bdc242bee0bb
Revises: 4296487095bc
Create Date: 2024-05-30 16:28:01.727135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc242bee0bb'
down_revision = '4296487095bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('logo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('logo')
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
