"""empty message

Revision ID: d5f39390c8db
Revises: b0fc6657cf33
Create Date: 2024-05-30 09:30:36.190478

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d5f39390c8db"
down_revision = "b0fc6657cf33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.add_column(sa.Column("home_team_score", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("away_team_score", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_column("away_team_score")
        batch_op.drop_column("home_team_score")

    # ### end Alembic commands ###
